language: generic
sudo: false
env:
  - EVM_EMACS=emacs-24.4-travis

before_install:
  # script to install emacs version manager and cask
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip

script:
  - emacs --batch -Q --eval '(message (emacs-version))'
  - make lint
